[package]
edition = "2021"
name = "fruity_ecs"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.14"
rayon = "1.5"
itertools = "0.10.1"
maplit = "1.0.2"
fruity_ecs_macro = { path = "../fruity_ecs_macro" }
fruity_game_engine = { path = "../fruity_game_engine" }

[features]
napi-module = [
    "napi-build",
    "fruity_game_engine/napi-module"
]

[build-dependencies]
napi-build = { version = "2.0.1", optional = true }

[profile.release]
lto = true
