[workspace]
resolver = "2"
members = [
  "./crates/fruity_game_engine",
  "./crates/fruity_game_engine_macro",
  "./crates/fruity_ecs",
  "./crates/fruity_ecs_macro",
  "./crates/fruity_hierarchy",
  "./examples/my_platformer/fruity_game_engine_bundle",
]