/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function World(): any;
export const readSettings: any;
export const createFruityEcsModule: any;
export const createFruityHierarchyModule: any;
export function sum(a: number, b: number): number;
