[package]
edition = "2021"
name = "fruity_game_engine"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
napi = { version = "2.10.0", default-features = false, features = ["napi4", "napi5", "napi6", "compat-mode"], optional = true }
puffin = "0.12.1"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
yaml-rust = "0.4"
lazy_static = "1.4.0"
linked-hash-map = "0.5.3"
convert_case = "0.6.0"
fruity_game_engine_macro = { path = "../fruity_game_engine_macro" }
napi-sys = "2.2.2"
send_wrapper = "0.6.0"

[features]
napi-module = [
    "napi",
    "napi-build",
    "fruity_game_engine_macro/napi-module"
]

[build-dependencies]
napi-build = { version = "2.0.1", optional = true }

[profile.release]
lto = true
